# Generated by Django 5.1.6 on 2025-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kpi_evaluation_evaluationkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='kpi_type',
            field=models.CharField(choices=[('score', 'Puntuación (0-10)'), ('percentage', 'Porcentaje (0-100%)'), ('amount', 'Monto (pesos)'), ('hours', 'Horas'), ('count', 'Cantidad')], default='score', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='max_value',
            field=models.FloatField(default=10.0, help_text='Valor máximo permitido'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='min_value',
            field=models.FloatField(default=0.0, help_text='Valor mínimo permitido'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unit',
            field=models.CharField(blank=True, help_text='Unidad de medida (ej: %, $, horas)', max_length=20),
        ),
    ]
