# Generated by Django 5.1.6 on 2025-09-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kpi_kpi_type_kpi_max_value_kpi_min_value_kpi_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiatorIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Tasa de conversión (%)')),
                ('total_revenue', models.FloatField(default=0.0, help_text='Recaudación total ($)')),
                ('absenteeism_rate', models.FloatField(default=0.0, help_text='Tasa de ausentismo (%)')),
                ('call_duration', models.FloatField(default=0.0, help_text='Duración promedio de llamadas (minutos)')),
                ('calls_made', models.IntegerField(default=0, help_text='Número de llamadas realizadas')),
                ('deals_closed', models.IntegerField(default=0, help_text='Acuerdos cerrados')),
                ('deals_failed', models.IntegerField(default=0, help_text='Acuerdos fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negotiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='accounts.negotiator')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('negotiator', 'date')},
            },
        ),
    ]
