# Generated by Django 5.1.6 on 2025-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_negotiatorindicator_absenteeism_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='conversion_de_ventas',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='porcentaje_caidas_acuerdos',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='porcentaje_cumplimiento_conversion',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='porcentajes_cumplimiento_recaudo',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='recaudacion_mensual',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='tiempo_hablando',
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='absenteeism_rate',
            field=models.FloatField(default=0.0, help_text='Tasa de ausentismo (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='call_duration',
            field=models.FloatField(default=0.0, help_text='Duración promedio de llamadas (minutos)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='calls_made',
            field=models.IntegerField(default=0, help_text='Número de llamadas realizadas'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='conversion_rate',
            field=models.FloatField(default=0.0, help_text='Tasa de conversión (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='deals_closed',
            field=models.IntegerField(default=0, help_text='Acuerdos cerrados'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='deals_failed',
            field=models.IntegerField(default=0, help_text='Acuerdos fallidos'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='total_revenue',
            field=models.FloatField(default=0.0, help_text='Recaudación total ($)'),
        ),
    ]
