# Generated by Django 5.1.6 on 2025-09-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_negotiatorindicator_conversion_de_ventas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='absenteeism_rate',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='call_duration',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='calls_made',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='deals_closed',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='deals_failed',
        ),
        migrations.RemoveField(
            model_name='negotiatorindicator',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='conversion_de_ventas',
            field=models.FloatField(default=0.0, help_text='Conversión de ventas (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='porcentaje_caidas_acuerdos',
            field=models.FloatField(default=0.0, help_text='Porcentaje de caídas de acuerdos (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='porcentaje_cumplimiento_conversion',
            field=models.FloatField(default=0.0, help_text='Porcentaje de cumplimiento de conversión (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='porcentajes_cumplimiento_recaudo',
            field=models.FloatField(default=0.0, help_text='Porcentaje de cumplimiento de recaudo (%)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='recaudacion_mensual',
            field=models.FloatField(default=0.0, help_text='Recaudación mensual ($)'),
        ),
        migrations.AddField(
            model_name='negotiatorindicator',
            name='tiempo_hablando',
            field=models.FloatField(default=0.0, help_text='Tiempo hablando (horas)'),
        ),
    ]
