# Generated by Django 5.2 on 2025-09-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_serquestion_evaluationser_delete_serevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationSer',
        ),
        migrations.DeleteModel(
            name='SerQuestion',
        ),
    ]
