# Generated by Django 5.2 on 2025-09-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_evaluationser_delete_serquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actitud', models.PositiveSmallIntegerField()),
                ('trabajo_en_equipo', models.PositiveSmallIntegerField()),
                ('sentido_pertenencia', models.PositiveSmallIntegerField()),
                ('relacionamiento', models.PositiveSmallIntegerField()),
                ('compromiso', models.PositiveSmallIntegerField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('negotiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ser_evaluations', to='accounts.negotiator')),
            ],
        ),
    ]
